colors = []

print("Time to build your dream house!")
start = input("Do you want to costomize the paint or randomize it?")

if(start == "randomize"):
   colors = ["black", "grey", "gold", "red", "orange", "yellow", "green", "blue", "purple", "pink"] 

if(start == "costomize"):
   color_1 = input("Lets start with color. What color do you want the main house?")
   color_2 = input("What color do you want the trim to be?")
   color_3 = input("What color do you want the door?")
   colors = [color_3, color_1, color_2]

shape = input("Finaly the shape. Do you wnat a square, rectangle, or double rectangle house?")
if(shape == "square"):
  size = input("Now lets consider the size. Do you wnat 1, 2, or 3 stories?")
elif(shape == "rectangle"):
  size = input("Now lets consider the size. Do you wnat 1, 2, or 3 stories?")
else:
  size = "1"

import turtle as trtl
trtl.pensize(5)

if(size == "1"):
    if(shape == "square"):
        #set colors
        new_color = colors.pop()
        trtl.pencolor(new_color)
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        #draw house
        trtl.penup()
        trtl.goto(-100,-100)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.forward(200)
          trtl.left(90)
          trtl.forward(200)
          trtl.left(90)
        trtl.end_fill()
        #draw roof
        trtl.penup()
        trtl.goto(100,100)
        trtl.left(90)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.left(60)
          trtl.forward(116)
        trtl.end_fill()
        #draw windows
        trtl.penup()
        trtl.goto(-35,50)
        trtl.right(30)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-60,50)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-35,25)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(80,50)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(55,50)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(80,25)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        #draw door
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.begin_fill()
        trtl.goto(18,-100)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(125)
        trtl.left(90)
        trtl.forward(40)
        trtl.left(90)
        trtl.forward(125)
        trtl.left(90)
        trtl.forward(40)
        trtl.end_fill()

    if(shape == "rectangle"):
        new_color = colors.pop()
        trtl.pencolor(new_color)
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.penup()
        trtl.goto(-100,0)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.forward(200)
          trtl.left(90)
          trtl.forward(100)
          trtl.left(90)
        trtl.end_fill()
        trtl.penup()
        trtl.goto(100,100)
        trtl.left(90)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.left(60)
          trtl.forward(117)
        trtl.end_fill()
        #draw windows
        trtl.penup()
        trtl.goto(-35,70)
        trtl.right(30)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-60,70)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-35,45)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(80,70)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(55,70)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(80,45)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        #draw door
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.begin_fill()
        trtl.goto(18, 0)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(80)
        trtl.left(90)
        trtl.forward(40)
        trtl.left(90)
        trtl.forward(80)
        trtl.left(90)
        trtl.forward(40)
        trtl.end_fill()

    if(shape == "double rectangle"):
        new_color = colors.pop()
        trtl.pencolor(new_color)
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        #rectangle 1
        trtl.penup()
        trtl.goto(25,0)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.forward(150)
          trtl.left(90)
          trtl.forward(150)
          trtl.left(90)
        #roof 1
        trtl.penup()
        trtl.goto(175,150)
        trtl.left(90)
        trtl.pendown()
        for i in range(2):
          trtl.left(60)
          trtl.forward(87)
        #rectangle 2
        trtl.penup()
        trtl.goto(25,0)
        trtl.left(150)
        trtl.pendown()
        for i in range(2):
          trtl.forward(-150)
          trtl.left(90)
          trtl.forward(100)
          trtl.left(90) 
        trtl.end_fill()
        #roof 2
        trtl.penup()
        trtl.left(90)
        trtl.goto(25,100)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.left(60)
          trtl.forward(85)
        trtl.end_fill()
        #draw window 1
        trtl.penup()
        trtl.goto(85,140)
        trtl.right(30)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(60,140)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(85,115)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        #draw window 2
        trtl.goto(160,140)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(135,140)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(160,115)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        #draw door
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.begin_fill()
        trtl.goto(120, 0)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(80)
        trtl.left(90)
        trtl.forward(40)
        trtl.left(90)
        trtl.forward(80)
        trtl.left(90)
        trtl.forward(40)
        trtl.end_fill()
        #draw garage door
        trtl.begin_fill()
        trtl.goto(-50, 0)
        trtl.pendown()
        trtl.forward(40)
        trtl.left(90)
        trtl.forward(80)
        trtl.left(90)
        trtl.forward(80)
        trtl.left(90)
        trtl.forward(80)
        trtl.left(90)
        trtl.forward(40)
        trtl.end_fill()

  
if(size == "2"):
    if(shape == "square"):
        new_color = colors.pop()
        trtl.pencolor(new_color)
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.penup()
        trtl.goto(-150,-150)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.forward(300)
          trtl.left(90)
          trtl.forward(300)
          trtl.left(90)
        trtl.end_fill()
        trtl.penup()
        trtl.goto(150,150)
        trtl.left(90)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.left(60)
          trtl.forward(175)
        trtl.end_fill()
        #draw window 1
        trtl.penup()
        trtl.goto(-70,-20)
        trtl.right(30)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-95,-20)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-70,-45)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 2
        trtl.goto(115,-20)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(90,-20)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(115,-45)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 3
        trtl.goto(-70,100)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-95,100)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-70,75)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 4
        trtl.goto(115,100)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(90,100)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(115,75)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 5
        trtl.goto(27,100)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(2,100)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(27,75)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        #draw door
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.begin_fill()
        trtl.goto(30, -150)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(150)
        trtl.left(90)
        trtl.forward(60)
        trtl.left(90)
        trtl.forward(150)
        trtl.left(90)
        trtl.forward(60)
        trtl.end_fill()

    if(shape == "rectangle"):
        new_color = colors.pop()
        trtl.pencolor(new_color)
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.penup()
        trtl.goto(-100,-150)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.forward(200)
          trtl.left(90)
          trtl.forward(300)
          trtl.left(90)
        trtl.end_fill()
        trtl.penup()
        trtl.goto(100,150)
        trtl.left(90)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.left(60)
          trtl.forward(117)
        trtl.end_fill()
         #draw window 1
        trtl.penup()
        trtl.goto(-35,-20)
        trtl.right(30)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-60,-20)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-35,-45)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 2
        trtl.goto(80,-20)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(55,-20)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(80,-45)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 3
        trtl.goto(-35,100)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-60,100)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-35,75)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 4
        trtl.goto(80,100)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(55,100)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(80,75)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        #draw door
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.begin_fill()
        trtl.goto(18, -150)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(150)
        trtl.left(90)
        trtl.forward(40)
        trtl.left(90)
        trtl.forward(150)
        trtl.left(90)
        trtl.forward(40)
        trtl.end_fill()
    
  
if(size == "3"):
    if(shape == "square"):
        new_color = colors.pop()
        trtl.pencolor(new_color)
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.penup()
        trtl.goto(-200,-200)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.forward(400)
          trtl.left(90)
          trtl.forward(400)
          trtl.left(90)
        trtl.end_fill()
        trtl.penup()
        trtl.goto(200,200)
        trtl.left(90)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.left(60)
          trtl.forward(232)
        trtl.end_fill()
        #draw window 1
        trtl.penup()
        trtl.goto(-90,-70)
        trtl.right(30)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-115,-70)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-90,-95)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 2
        trtl.goto(135,-70)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(110,-70)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(135,-95)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 3
        trtl.goto(-90,50)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-115,50)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-90,25)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 4
        trtl.goto(135,50)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(110,50)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(135,25)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 5
        trtl.goto(27,50)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(2,50)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(27,25)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 6
        trtl.goto(-33,150)
        trtl.pendown()
        for i in range(2):
           trtl.forward(100)
           trtl.left(90)
           trtl.forward(50)
           trtl.left(90)
        trtl.penup()
        trtl.goto(-83,150)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-33,125)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(100)
        trtl.penup()
         #draw window 7
        trtl.goto(127,150)
        trtl.pendown()
        for i in range(2):
          trtl.forward(100)
          trtl.left(90)
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(77,150)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(127,125)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(100)
        trtl.penup()
        #draw door
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.begin_fill()
        trtl.goto(30, -200)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(150)
        trtl.left(90)
        trtl.forward(60)
        trtl.left(90)
        trtl.forward(150)
        trtl.left(90)
        trtl.forward(60)
        trtl.end_fill()

    if(shape == "rectangle"):
        new_color = colors.pop()
        trtl.pencolor(new_color)
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.penup()
        trtl.goto(-150,-200)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.forward(300)
          trtl.left(90)
          trtl.forward(400)
          trtl.left(90)
        trtl.end_fill()
        trtl.penup()
        trtl.goto(150,200)
        trtl.left(90)
        trtl.pendown()
        trtl.begin_fill()
        for i in range(2):
          trtl.left(60)
          trtl.forward(175)
        trtl.end_fill()
         #draw window 1
        trtl.penup()
        trtl.goto(-55,-70)
        trtl.right(30)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-80,-70)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-55,-95)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 2
        trtl.goto(100,-70)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(75,-70)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(100,-95)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 3
        trtl.goto(-55,50)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(-80,50)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(-55,25)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
         #draw window 4
        trtl.goto(100,50)
        trtl.pendown()
        for i in range(4):
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(75,50)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(100,25)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(50)
        trtl.penup()
        #draw window 5
        trtl.goto(50,150)
        trtl.pendown()
        for i in range(2):
          trtl.forward(100)
          trtl.left(90)
          trtl.forward(50)
          trtl.left(90)
        trtl.penup()
        trtl.goto(0,150)
        trtl.pendown()
        trtl.left(90)
        trtl.forward(50)
        trtl.penup()
        trtl.goto(50,125)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(100)
        trtl.penup()
        #draw door
        new_color = colors.pop()
        trtl.fillcolor(new_color)
        trtl.begin_fill()
        trtl.goto(18, -200)
        trtl.pendown()
        trtl.right(90)
        trtl.forward(150)
        trtl.left(90)
        trtl.forward(40)
        trtl.left(90)
        trtl.forward(150)
        trtl.left(90)
        trtl.forward(40)
        trtl.end_fill()

   
  

wn = trtl.Screen()
wn.mainloop()
